---
title: "P8105_HW_sm5567"
author: Shina Min
date: September 2023
output:
  github_document:
    toc: true
---


# Section 1

* The variables in this dataset: 15 variables including origin, year, month, day, hour, temp, dewp, humid, wind_dir, wind_speed, wind_qust, precip, pressure, visib, and time_hour. 

* This dataset has 358 entries. 

* The dataset has `r nrow ("early_january_weather")` 15 rows and
`r ncol("early_january_weather")` 358 columns.

* The mean of temperature is 39.58212


```{r}

library(ggplot2)
library(moderndive)
library(tidyverse)
data("early_january_weather")

n_rows <- nrow(early_january_weather)
n_cols <- ncol(early_january_weather)

mean_temp <- mean(early_january_weather$temp) 
mean(pull(early_january_weather,'temp'))
     
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + 
  geom_point() + labs(x = "Time Hour", y = "Temperature", color = "Humidity")

ggsave("Shinaplot.pdf",plot = last_plot())

```


# Section 2

* Data frame comprised of: 

```{r s2_df_create}
samp = rnorm(10)
length(samp)

s2_df = tibble(
  samp = rnorm(10, sd = 1),
  vec_logical = samp > 0,
  vec_char = c("a", "b", "c", "d", "e", "f", "g", "h", "i","j"),
  vec_factor = factor(c("red", "green", "blue","red", "green", "blue", "red","green","blue", "red"))
)
```


